[package]
name = "laporan-bulanan"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
slint = { version = "1.17", features = ["backend-android-activity-06"] }
rusqlite = { version = "0.31", features = ["bundled"] }
chrono = "0.4"
rust_xlsxwriter = "0.99.0"
genpdf = { version = "0.2.0", features = ["images"] }

[build-dependencies]
slint-build = "1.17"

[package.metadata.android]
package = "com.roguenine.laporan_bulanan_v2"
build_targets = ["aarch64-linux-android"]
apk_name = "LaporanBulanan"
permissions = [
    "android.permission.READ_EXTERNAL_STORAGE",
    "android.permission.WRITE_EXTERNAL_STORAGE",
    "android.permission.CAMERA"
]

[package.metadata.android.application]
label = "Laporan Bulanan"

[package.metadata.android.sdk]
target_sdk_version = 33

[package.metadata.android.signing.release]
path = "release.keystore"
keystore_password = "password"
key_alias = "release"
key_password = "password"
